# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.9.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computations **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [15]:
sess.close()

## Operations

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [23]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.19019324  0.21049517  0.05803382  0.4133758 ]
 [ 0.3214004   0.437334   -0.17611076 -0.21004625]
 [ 0.08248034  0.33433065  0.34096786  0.80340356]
 [-0.2429891   0.95711195 -0.3656966   0.12912153]]


[[0.17455244 0.36347806 0.7832098  0.3443315 ]
 [0.40889478 0.14890969 0.9799094  0.23348689]
 [0.64944744 0.7275984  0.9859576  0.10855651]
 [0.92117333 0.9986497  0.1174829  0.8085761 ]]




## Matrix Multiplication

In [25]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [26]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [27]:
b = tf.constant([[10],[100]])

In [28]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [29]:
result = tf.matmul(a,b)

In [30]:
result.eval()

array([[210],
       [430]])