<center><img src="../../Pics/MLSb-T.png" width="160"></center>
<br><br>

<center><u><H1>NUMPY</H1><u></center>   

In [1]:
import numpy as np

<b>Creating an array:</b>

In [2]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<b>Check the attributes:</b>

In [3]:
arr.ndim

2

In [4]:
arr.shape

(3L, 3L)

In [5]:
arr.size

9

In [6]:
arr.dtype.name

'int32'

<H3>Mathematical Operations:</H3>

In [7]:
#Substraction
a = np.array([6,5,4,8])
b = np.array([1,2,5,10])
a-b

array([ 5,  3, -1, -2])

In [8]:
#Squaring an array
b**2

array([  1,   4,  25, 100])

In [9]:
#Applying trigonometic functions
np.sin(b)

array([ 0.84147098,  0.90929743, -0.95892427, -0.54402111])

In [10]:
#Conditional operations
b>1

array([False,  True,  True,  True])

In [11]:
#Matrix multiplication
M1 = np.array([[1,2],[0,1]])
M2 = np.array([[-1,0],[1,1]])
M1*M2

array([[-1,  0],
       [ 0,  1]])

In [12]:
#The dot product
np.dot(M1,M2)

array([[1, 2],
       [1, 1]])

<h3>Indexing and slicing:</h3>

In [13]:
#Index positions
a = np.array([[3,4,5],[7,8,3],[0,3,23],[8,11,6]])
a[1,1]

8

In [14]:
a[0,0:2]

array([3, 4])

In [15]:
a[0,:]

array([3, 4, 5])

In [16]:
a[:,1]

array([ 4,  8,  3, 11])

In [17]:
a[:,-1]

array([ 5,  3, 23,  6])

### Shape Manipulation:

In [18]:
a.ravel()

array([ 3,  4,  5,  7,  8,  3,  0,  3, 23,  8, 11,  6])

In [19]:
a.shape=(6,2)
a

array([[ 3,  4],
       [ 5,  7],
       [ 8,  3],
       [ 0,  3],
       [23,  8],
       [11,  6]])

In [20]:
a.transpose()

array([[ 3,  5,  8,  0, 23, 11],
       [ 4,  7,  3,  3,  8,  6]])

In [21]:
c = np.linspace(-2,2,20)
c

array([-2.        , -1.78947368, -1.57894737, -1.36842105, -1.15789474,
       -0.94736842, -0.73684211, -0.52631579, -0.31578947, -0.10526316,
        0.10526316,  0.31578947,  0.52631579,  0.73684211,  0.94736842,
        1.15789474,  1.36842105,  1.57894737,  1.78947368,  2.        ])

In [22]:
# NEW AXIS
x1 = np.array([1, 2, 3, 4, 5])
x1_new = x1[:, np.newaxis]
x1_new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [23]:
x2 = np.array([5, 4, 3])
x3 = x1_new + x2
x3

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [24]:
x3_new = x3[:,np.newaxis,1]
x3_new

array([[5],
       [6],
       [7],
       [8],
       [9]])

## Reference:

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html